apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice-service
spec:
  selector:
    tier: calculator-microservice-frontend
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  ports:
  - name: calculator-microservice-port
    port: 8037
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  